SignalRWebUI/Areas/Admin/Controllers/ProfileSettingController.cs
using Microsoft.AspNetCore.Mvc;
using SignalRWebUI.Dtos.IdentityDtos;
using SignalRWebUI.Services.Abstract.IdentityServices;
using System.Security.Claims;

namespace SignalRWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/ProfileSetting")]
    public class ProfileSettingController : AdminBaseController
    {
        private readonly IUserProfileChangeServicePS _userProfileChangeServicePS;

        public ProfileSettingController(IUserProfileChangeServicePS userProfileChangeServicePS)
        {
            _userProfileChangeServicePS = userProfileChangeServicePS;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.MainTitle = "Kullanıcı Bilgileri Güncelleme";

            UserEditDto model = new UserEditDto();

            var userID = User?.FindFirstValue("sub");

            var values = await _userProfileChangeServicePS.GetUserInfoAsync(userID);

            model.UserData = values.GetData;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(UserEditDto userEditDto)
        {
            var values = await _userProfileChangeServicePS.ChangeUserInfoAsync(userEditDto);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("ChangePassword")]
        public async Task<IActionResult> ChangePassword()
        {
            ViewBag.MainTitle = "Şifre Güncelleme";

            UserEditDto model = new UserEditDto();

            return View(model);
        }

        [HttpPost]
        [Route("ChangePassword")]
        public async Task<IActionResult> ChangePassword(UserEditDto userEditDto)
        {

            var userID = User?.FindFirstValue("sub");

            var responseUserData = await _userProfileChangeServicePS.GetUserInfoAsync(userID);

            userEditDto.UserData = responseUserData.GetData;

            var values = await _userProfileChangeServicePS.ChangeUserPasswordAsync(userEditDto);

            return RedirectToAction("Index");
        }
    }
}

SignalRWebUI/Areas/User/Controllers/ProfileSettingController.cs
using Microsoft.AspNetCore.Mvc;
using SignalRWebUI.Dtos.IdentityDtos;
using SignalRWebUI.Services.Abstract.IdentityServices;
using System.Security.Claims;

namespace SignalRWebUI.Areas.User.Controllers
{
    [Area("User")]
    [Route("User/ProfileSetting")]
    public class ProfileSettingController : BaseUserController
    {
        private readonly IUserProfileChangeServicePS _userProfileChangeServicePS;

        public ProfileSettingController(IUserProfileChangeServicePS userProfileChangeServicePS)
        {
            _userProfileChangeServicePS = userProfileChangeServicePS;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.MainTitle = "Kullanıcı Bilgileri Güncelleme";

            UserEditDto model = new UserEditDto();

            var userID = User?.FindFirstValue("sub");

            var values = await _userProfileChangeServicePS.GetUserInfoAsync(userID);

            model.UserData = values.GetData;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(UserEditDto userEditDto)
        {
            var values = await _userProfileChangeServicePS.ChangeUserInfoAsync(userEditDto);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("ChangePassword")]
        public async Task<IActionResult> ChangePassword()
        {
            ViewBag.MainTitle = "Şifre Güncelleme";

            UserEditDto model = new UserEditDto();

            return View(model);
        }

        [HttpPost]
        [Route("ChangePassword")]
        public async Task<IActionResult> ChangePassword(UserEditDto userEditDto)
        {

            var userID = User?.FindFirstValue("sub");

            var responseUserData = await _userProfileChangeServicePS.GetUserInfoAsync(userID);

            userEditDto.UserData = responseUserData.GetData;

            var values = await _userProfileChangeServicePS.ChangeUserPasswordAsync(userEditDto);

            return RedirectToAction("Index");
        }
    }
}

SignalRWebUI/Areas/Admin/Views/ProfileSetting/ChangePassword.cshtml
@model UserEditDto

@{
    ViewData["Title"] = "Şifre Değişikliği";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    string mainTitle = (string)ViewBag.MainTitle;
}


<form id="ChangePasswordForm" asp-area="Admin" asp-controller="ProfileSetting" asp-action="ChangePassword" method="post">
    <div class="content">
        <div class="container-fluid">
            <h5>@mainTitle</h5>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Şifre Güncelleme</div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                @Html.HiddenFor(x => x.UserData.Id)
                                <div class="col-md-6 form-group">
                                    <label asp-for="EdittedPassword">Yeni Şifreniz</label>
                                    <input asp-for="EdittedPassword" type="text" class="form-control input-square" placeholder="Yeni Şifreniz">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <a href="/admin/dashboard" class="btn btn-outline-danger"><i class="la la-times"></i> Vazgeç</a>
                        <button type="submit" class="btn btn-success"><i class="la la-edit"></i> Güncelle</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

SignalRWebUI/Areas/Admin/Views/ProfileSetting/Index.cshtml
@model UserEditDto

@{
    ViewData["Title"] = "Profil Bilgileri";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    string mainTitle = (string)ViewBag.MainTitle;
}

<form id="UserDataEditForm" asp-area="Admin" asp-controller="ProfileSetting" asp-action="Index" method="post">
    <div class="content">
        <div class="container-fluid">
            <h5>@mainTitle</h5>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Kullanıcı Bilgisi Güncelleme</div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                @Html.HiddenFor(x => x.UserData.Id)
                                <div class="col-md-6 form-group">
                                    <label asp-for="UserData.Name">Adınız</label>
                                    <input asp-for="UserData.Name" type="text" class="form-control input-square" placeholder="Adınız">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label asp-for="UserData.Surname">Soyadınız</label>
                                    <input asp-for="UserData.Surname" type="text" class="form-control input-square" placeholder="Soyadınız">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label asp-for="UserData.UserName">Kullanıcı Adınız</label>
                                    <input asp-for="UserData.UserName" type="text" class="form-control input-square" placeholder="Kullanıcı Adınız">
                                </div>
                                <div class="col-md-2 form-group">
                                    <label for="UserPasswordChange">Şifre Değişikliği</label>
                                    <a href="/admin/profilesetting/changepassword" id="UserPasswordChange" class="form-control btn btn-primary"><i class="la la-key"></i> Şifre Değiştir</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <a href="/admin/dashboard" class="btn btn-outline-danger"><i class="la la-times"></i> Vazgeç</a>
                        <button type="submit" class="btn btn-success"><i class="la la-edit"></i> Güncelle</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>