SignalRWebUI/Areas/Admin/Models/TestimonialViewModel.cs
using SignalR.Dtos.Dtos.TestimonialDtos;
using SignalRWebUI.Areas.Admin.Dtos.TestimonialDtos;

namespace SignalRWebUI.Areas.Admin.Models
{
    public class TestimonialViewModel : GenericViewModel
    {
        public List<ResultTestimonialDto> ResultTestimonials { get; set; }
        public CreateAdminTestimonialDto CreateTestimonial { get; set; }
        public UpdateAdminTestimonialDto UpdateTestimonial { get; set; }
    }
}

SignalRWebUI/Areas/Admin/Controllers/TestimonialController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using SignalR.Dtos.Dtos.TestimonialDtos;
using SignalRWebUI.Areas.Admin.Dtos.TestimonialDtos;
using SignalRWebUI.Areas.Admin.Models;
using SignalRWebUI.Services.Abstract;
using SignalRWebUI.Settings;
using SignalRWebUI.Utilities.FileOperations;
using System.Net;

namespace SignalRWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Testimonial")]
    public class TestimonialController : AdminBaseController
    {
        private readonly ITestimonialServicePS _testimonialService;
        private readonly IMapper _mapper;
        private readonly IFileOperation _fileOperation;

        public TestimonialController(ITestimonialServicePS testimonialService, IMapper mapper, IFileOperation fileOperation)
        {
            _testimonialService = testimonialService;
            _mapper = mapper;
            _fileOperation = fileOperation;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.MainTitle = "Yorumlar";
            ViewBag.EmptyDataInfo = "Yorum";

            var responseMessage = await _testimonialService.GetAllDataAsync(null);

            TestimonialViewModel model = new TestimonialViewModel();

            if (responseMessage.StatusMessage == HttpStatusCode.OK)
            {
                List<ResultTestimonialDto> values = responseMessage.GetData;
                model.ResultTestimonials = values;
            }

            return View(model);
        }

        [HttpGet]
        [Route("Create")]
        public async Task<IActionResult> CreateTestimonial()
        {
            ViewBag.MainTitle = "Yorumlar";

            TestimonialViewModel model = new TestimonialViewModel();

            return View(model);
        }

        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> CreateTestimonial(TestimonialViewModel testimonialViewModel)
        {

            string imageUrl = await SaveImageFileAsync(testimonialViewModel.CreateTestimonial.Image);
            testimonialViewModel.CreateTestimonial.ImageUrl = imageUrl;

            var response = await _testimonialService.CreateDataAsync(testimonialViewModel.CreateTestimonial);

            if (response.StatusMessage == HttpStatusCode.OK)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ResponseMessage = $"Yorum Eklenirken Bir Hata Oluştu! StatusCode: {response.StatusCode}";

                testimonialViewModel.HttpResponseMessage = response.StatusMessage;
                testimonialViewModel.ApiResponseMessage = response.ApiResponseMessage;
            }

            return View(testimonialViewModel);
        }

        [HttpGet]
        [Route("Update/{id}")]
        public async Task<IActionResult> UpdateTestimonial(int id)
        {
            ViewBag.MainTitle = "Yorumlar";

            var responseMessage = await _testimonialService.GetDataAsync(id);

            TestimonialViewModel model = new TestimonialViewModel();

            if (responseMessage.StatusMessage == HttpStatusCode.OK)
            {
                UpdateAdminTestimonialDto values = _mapper.Map<UpdateAdminTestimonialDto>(responseMessage.GetData);
                model.UpdateTestimonial = values;
            }

            ViewBag.ResponseMessage = $"Yorum Listelenirken Bir Hata Oluştu! StatusCode: {responseMessage.StatusCode}";

            responseMessage.StatusMessage = responseMessage.StatusMessage;

            return View(model);
        }

        [HttpPost]
        [Route("Update/{id}\")")]
        public async Task<IActionResult> UpdateTestimonial(TestimonialViewModel testimonialViewModel)
        {
            if (testimonialViewModel.UpdateTestimonial.Image != null)
            {
                string imageUrl = await SaveImageFileAsync(testimonialViewModel.UpdateTestimonial.Image);
                testimonialViewModel.UpdateTestimonial.ImageUrl = imageUrl;
            }

            var response = await _testimonialService.UpdateDataAsync(testimonialViewModel.UpdateTestimonial);

            if (response.StatusMessage == HttpStatusCode.OK)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ResponseMessage = $"Yorum Güncellenirken Bir Hata Oluştu! StatusCode: {response.StatusCode}";

                testimonialViewModel.HttpResponseMessage = response.StatusMessage;
                testimonialViewModel.ApiResponseMessage = response.ApiResponseMessage;
            }

            return View(testimonialViewModel);
        }

        [HttpGet]
        [Route("Delete")]
        public async Task<IActionResult> DeleteTestimonial(int id)
        {
            await _testimonialService.DeleteDataAsync(id);

            return RedirectToAction("Index");
        }

        private async Task<string> SaveImageFileAsync(IFormFile imageFile)
        {
            FileSettings fileSettings = new FileSettings
            {
                FolderPath = "\\wwwroot\\asset",
                FolderName = "defaultimage",
                UploadFile = imageFile
            };

            return await _fileOperation.SaveFileAsync(fileSettings);
        }
    }
}

SignalRWebUI/Areas/Admin/Views/Testimonial/CreateTestimonial.cshtml
@model TestimonialViewModel

@{
    ViewData["Title"] = "Yeni Yorum Ekleme";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    string mainTitle = (string)ViewBag.MainTitle;
    string[] validationErrors = Model?.ApiResponseMessage?.Split(",");
}

<form id="AddNewTestimonialForm" asp-area="Admin" asp-controller="Testimonial" asp-action="CreateTestimonial" method="post" enctype="multipart/form-data">

    <div class="content">
        <div class="container-fluid">
            <h5>@mainTitle</h5>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Yeni Yorum Ekleme</div>
                        </div>
                        <div class="card-body">
                            @if (Model.HttpResponseMessage != 0)
                            {
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="alert alert-danger text-center">
                                            @foreach (var errorItem in validationErrors)
                                            {
                                                <span>@errorItem</span>
                                                @if (errorItem != validationErrors.Last())
                                                {
                                                    <br />
                                                }
                                            }
                                        </p>
                                    </div>
                                </div>
                            }
                            <div class="row">
                                <div class="col-md-4 form-group">
                                    <label asp-for="CreateTestimonial.Name">Kullanıcı Adı</label>
                                    <input asp-for="CreateTestimonial.Name" type="text" class="form-control input-square" placeholder="Kullanıcı Adı">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label asp-for="CreateTestimonial.Image">Yorum Görseli</label>
                                    <input asp-for="CreateTestimonial.Image" type="file" class="form-control input-square">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label asp-for="CreateTestimonial.Status">Yorum Durumu</label>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input asp-for="CreateTestimonial.Status" class="form-check-input" type="checkbox">
                                            <span class="form-check-sign">Aktif</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label asp-for="CreateTestimonial.Title">Yorum Başlığı</label>
                                    <input asp-for="CreateTestimonial.Title" type="text" class="form-control input-square" placeholder="Yorum Başlığı">
                                </div>
                                <div class="col-md-12 form-group">
                                    <label asp-for="CreateTestimonial.Comment">Açıklama</label>
                                    <textarea asp-for="CreateTestimonial.Comment" rows="5" class="form-control input-square" placeholder="Açıklama"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <a href="/admin/testimonial" class="btn btn-outline-danger"><i class="la la-times"></i> Vazgeç</a>
                        <button type="submit" class="btn btn-success"><i class="la la-plus"></i> Kaydet</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

SignalRWebUI/Areas/Admin/Views/Testimonial/Index.cshtml
@model TestimonialViewModel

@{
    ViewData["Title"] = "Referanslar";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    string mainTitle = (string)ViewBag.MainTitle;
    string emptyDataInfo = (string)ViewBag.EmptyDataInfo;
}

<div class="content">
    <div class="container-fluid">
        <h5>@mainTitle</h5>
        <div class="row">
            @if (Model.ResultTestimonials != null)
            {
                @if (Model.ResultTestimonials.Count() > 0)
                {
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">Yorum Listesi</div>
                            </div>
                            <div class="card-body">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Kulllanıcı Adı</th>
                                            <th scope="col">Başlık</th>
                                            <th scope="col">Durum</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.ResultTestimonials)
                                        {
                                            <tr>
                                                <td>@item.TestimonialID</td>
                                                <td>@item.Name</td>
                                                <td>@item.Title <a href="~/asset/defaultimage/@item.ImageUrl" target="_blank"><i class="la la-image"></i></a></td>
                                                @if (item.Status)
                                                {
                                                    <td><div class="badge badge-success">Aktif</div></td>
                                                }
                                                else
                                                {
                                                    <td><div class="badge badge-danger">Pasif</div></td>
                                                }
                                                <td>
                                                    <a href="/admin/testimonial/delete?id=@item.TestimonialID" class="btn btn-outline-danger"><i class="la la-trash"></i></a>
                                                    <a href="/admin/testimonial/update/@item.TestimonialID" class="btn btn-outline-info"><i class="la la-edit"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="alert alert-info w-100 text-center">Henüz Kayıtlı Bir @emptyDataInfo Bulunmuyor!</div>
                }
                <a href="/admin/testimonial/create" class="btn btn-success"><i class="la la-plus"></i> Yeni Yorum Ekle</a>
            }
            else
            {
                <div class="alert alert-danger w-100 text-center">@Model.HttpResponseMessage !</div>
            }
        </div>
    </div>
</div>

SignalRWebUI/Areas/Admin/Views/Testimonial/UpdateTestimonial.cshtml
@model TestimonialViewModel

@{
    ViewData["Title"] = "Yorum Güncelleme";
    Layout = "~/Views/AdminLayout/Index.cshtml";
    string mainTitle = (string)ViewBag.MainTitle;
    string[] validationErrors = Model?.ApiResponseMessage?.Split(",");
}

<form id="UpdateTestimonialForm" asp-area="Admin" asp-controller="Testimonial" asp-action="UpdateTestimonial" method="post" enctype="multipart/form-data">

    <div class="content">
        <div class="container-fluid">
            <h5>@mainTitle</h5>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Yorum Güncelleme</div>
                        </div>
                        <div class="card-body">
                            @if (Model.HttpResponseMessage != 0)
                            {
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="alert alert-danger text-center">
                                            @foreach (var errorItem in validationErrors)
                                            {
                                                <span>@errorItem</span>
                                                @if (errorItem != validationErrors.Last())
                                                {
                                                    <br />
                                                }
                                            }
                                        </p>
                                    </div>
                                </div>
                            }
                            <div class="row">
                                @Html.HiddenFor(x => x.UpdateTestimonial.TestimonialID)
                                @Html.HiddenFor(x => x.UpdateTestimonial.ImageUrl)
                                <div class="col-md-4 form-group">
                                    <label asp-for="UpdateTestimonial.Name">Kullanıcı Adı</label>
                                    <input asp-for="UpdateTestimonial.Name" type="text" class="form-control input-square" placeholder="Kullanıcı Adı">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label asp-for="UpdateTestimonial.Image">Yorum Görseli <a href="~/asset/defaultimage/@Model.UpdateTestimonial.ImageUrl" target="_blank"><i class="la la-image"></i></a></label>
                                    <input asp-for="UpdateTestimonial.Image" type="file" class="form-control input-square">
                                </div>
                                <div class="col-md-4 form-group">
                                    <label asp-for="UpdateTestimonial.Status">Yorum Durumu</label>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input asp-for="UpdateTestimonial.Status" class="form-check-input" type="checkbox">
                                            <span class="form-check-sign">Aktif</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label asp-for="UpdateTestimonial.Title">Yorum Başlığı</label>
                                    <input asp-for="UpdateTestimonial.Title" type="text" class="form-control input-square" placeholder="Yorum Başlığı">
                                </div>
                                <div class="col-md-12 form-group">
                                    <label asp-for="UpdateTestimonial.Comment">Açıklama</label>
                                    <textarea asp-for="UpdateTestimonial.Comment" rows="5" class="form-control input-square" placeholder="Açıklama"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <a href="/admin/testimonial" class="btn btn-outline-danger"><i class="la la-times"></i> Vazgeç</a>
                        <button type="submit" class="btn btn-success"><i class="la la-plus"></i> Güncelle</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>