SignalRWebUI/Controllers/QRCodeController.cs
using Microsoft.AspNetCore.Mvc;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace SignalRWebUI.Controllers
{
    public class QRCodeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string value)
        {
            using (MemoryStream memoryStream = new MemoryStream())
            {
                QRCodeGenerator createQRCode = new QRCodeGenerator();

                QRCodeGenerator.QRCode squareCode = createQRCode.CreateQrCode(value, QRCodeGenerator.ECCLevel.Q);

                using (Bitmap image = squareCode.GetGraphic(10))
                {
                    image.Save(memoryStream, ImageFormat.Png);
                    ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(memoryStream.ToArray());
                }
            }

            return View();
        }
    }
}

SignalRWebUI/Views/QRCode/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<form id="NewQRCodeGeneratorForm" asp-controller="QRCode" asp-action="Index">
    <div class="content">
        <div class="container-fluid">
            <h5>@ViewBag.MainTitle</h5>
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">QR Kod İşlemleri</div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="text" name="value" />
                                <input type="submit" value="QR Kod Oluştur" class="btn btn-warning" />
                            </div>
                        </div>
                    </div>
                </div>

                @if (ViewBag.QRCodeImage != null)
                {
                    <div class="col-md-6">
                        <img src="@ViewBag.QRCodeImage" alt="QRCode" style="width: 400px; height:400px;" />
                    </div>
                }
            </div>
        </div>
    </div>
</form>